Improve README
vcaesar/riot pull request #8
Opened 2017-10-25 14:40 UTC by lokeshh

Remove useless $

2017-10-25 16:48 UTC, mariida reviewed
SOME THING FOUN ERROR

2017-10-26 07:24 UTC, vcaesar commented
Thank you for your pr, reserve one's opinion, please see [dep](https://github.com/golang/dep) , [gin](https://github.com/gin-gonic/gin) and [bee](https://github.com/beego/bee)'s README.md.

2017-10-26 07:31 UTC, vcaesar requested changes
`$` Is the normal user's prompt.

2017-10-26 13:49 UTC, lokeshh commented
@vcaesar I agree but it makes things hard to copy paste. Further for the first two commands you don't have `$`, hence it isn't consistent.

2017-10-26 14:13 UTC, vcaesar commented
@lokeshh Ok, let me think about it.

2017-10-29 07:28 UTC, bettylily approved these changes

2019-08-08 12:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/go-ego/riot?pullRequest=8) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/go-ego/riot?pullRequest=8) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/go-ego/riot?pullRequest=8) it.</sub>

2026-09-10 12:21 UTC, closed without merging